export const DEFAULT_CATEGORIES = [
  { id: 'food',          name: 'Food',          emoji: '🍔', color: '#d47050' },
  { id: 'groceries',     name: 'Groceries',     emoji: '🛒', color: '#7aaa58' },
  { id: 'transport',     name: 'Transport',     emoji: '🚗', color: '#5580b8' },
  { id: 'shopping',      name: 'Shopping',      emoji: '🛍️', color: '#b070c0' },
  { id: 'bills',         name: 'Bills',         emoji: '📄', color: '#c8a840' },
  { id: 'rent',          name: 'Rent',          emoji: '🏠', color: '#6a4c38' },
  { id: 'entertainment', name: 'Entertainment', emoji: '🎮', color: '#4daa88' },
  { id: 'health',        name: 'Health',        emoji: '💊', color: '#c06888' },
  { id: 'education',     name: 'Education',     emoji: '📚', color: '#7070c8' },
  { id: 'travel',        name: 'Travel',        emoji: '✈️', color: '#4ab0c0' },
  { id: 'other',         name: 'Other',         emoji: '📦', color: '#908878' },
];

export const DEFAULT_MERCHANT_RULES = [
  // Food
  { keyword: 'swiggy',      categoryId: 'food' },
  { keyword: 'zomato',      categoryId: 'food' },
  { keyword: 'dominos',     categoryId: 'food' },
  { keyword: 'pizza',       categoryId: 'food' },
  { keyword: 'mcdonald',    categoryId: 'food' },
  { keyword: 'kfc',         categoryId: 'food' },
  { keyword: 'restaurant',  categoryId: 'food' },
  { keyword: 'cafe',        categoryId: 'food' },
  { keyword: 'starbucks',   categoryId: 'food' },
  { keyword: 'blinkit',     categoryId: 'groceries' },
  { keyword: 'zepto',       categoryId: 'groceries' },
  { keyword: 'bigbasket',   categoryId: 'groceries' },
  { keyword: 'dmart',       categoryId: 'groceries' },
  { keyword: 'grofers',     categoryId: 'groceries' },
  { keyword: 'jiomart',     categoryId: 'groceries' },
  // Transport
  { keyword: 'uber',        categoryId: 'transport' },
  { keyword: 'ola',         categoryId: 'transport' },
  { keyword: 'rapido',      categoryId: 'transport' },
  { keyword: 'metro',       categoryId: 'transport' },
  { keyword: 'irctc',       categoryId: 'transport' },
  { keyword: 'makemytrip',  categoryId: 'travel' },
  { keyword: 'indigo',      categoryId: 'travel' },
  { keyword: 'airasia',     categoryId: 'travel' },
  { keyword: 'oyo',         categoryId: 'travel' },
  // Shopping
  { keyword: 'amazon',      categoryId: 'shopping' },
  { keyword: 'flipkart',    categoryId: 'shopping' },
  { keyword: 'myntra',      categoryId: 'shopping' },
  { keyword: 'meesho',      categoryId: 'shopping' },
  { keyword: 'ajio',        categoryId: 'shopping' },
  { keyword: 'nykaa',       categoryId: 'shopping' },
  // Bills / Utilities
  { keyword: 'airtel',      categoryId: 'bills' },
  { keyword: 'jio',         categoryId: 'bills' },
  { keyword: 'vi ',         categoryId: 'bills' },
  { keyword: 'electricity', categoryId: 'bills' },
  { keyword: 'broadband',   categoryId: 'bills' },
  { keyword: 'netflix',     categoryId: 'entertainment' },
  { keyword: 'spotify',     categoryId: 'entertainment' },
  { keyword: 'hotstar',     categoryId: 'entertainment' },
  { keyword: 'prime video', categoryId: 'entertainment' },
  // Health
  { keyword: 'apollo',      categoryId: 'health' },
  { keyword: 'medplus',     categoryId: 'health' },
  { keyword: 'pharmacy',    categoryId: 'health' },
  { keyword: 'hospital',    categoryId: 'health' },
  { keyword: 'clinic',      categoryId: 'health' },
];

